### ISSUE TITLE
Visual artifacts

### ISSUE THREAD

**Issue by 875d** [marty-oehme/bemoji#17]
The bemoji window also flickers but that apparently isn't captured by OBS Studio:

![output](https://user-images.githubusercontent.com/118444583/204509759-6e513595-2b9b-4e64-bb7d-1332a68b1b67.gif)

**Comment by marty-oehme** [comment]
That is very interesting. Are you running on X11 or on Wayland? 

And does the issue happen when you open rofi (which I believe is your picker?) manually while displaying emojis? E.g.:

```bash
echo -e "😀 grinning face\n😃 grinning face with big eyes" | rofi -dmenu
```

**Comment by 875d** [comment]
I'm on Wayland.

I discovered like after I opened this issue that I could pipe the output to my favourite dmenu-like picker, which is fuzzel.

So right now I'm using 
```
BEMOJI_PICKER_CMD="fuzzel --dmenu" bemoji -P -t
```

which works wonders.

The artifacts only happen when calling `bemoji` directly.

**Comment by 875d** [comment]
Uhm I actually had rofi installed. I uninstalled it and now bemoji doesn't start on itself.

So I guess it was a bug of rofi?

**Comment by marty-oehme** [comment]
My guess would be then that it tried to start rofi by default - which had to be started under XWayland - and some geometry-setting didn't work out right under Wayland proper. Perhaps I could show a warning if rofi is (automatically) started under Wayland.

Also, fuzzel seems like an interesting dmenu-like, thanks for bringing it to my attention!

**Comment by 875d** [comment]
Oh, rofi is only for X11. That could explain it.
