### ISSUE TITLE
Bump to Emoji 15.0

### ISSUE THREAD

**Issue by vaygr** [marty-oehme/bemoji#18]
I miss the 🪿.

And maybe it makes sense to put URLs for both emojis and math symbols at the top as variables, so all hardcoded values are clearly visible and not buried in the code.

**Comment by marty-oehme** [comment]
Thanks for the report, that is really good input!

I do not remember why I chose the hard-coded '14.0' emoji download link but we can definitely use `https://unicode.org/Public/emoji/latest/emoji-test.txt` instead to always grab the latest. 

And I think it is also a good point to extract the magic URL values somewhere to the top. I am still considering moving the whole downloading portion into a separate executable but this is a good first step to remove some 'magic' from it.

I'll definitely get around to the changes but am also happy to merge a little PR if you're inclined!

**Comment by marty-oehme** [comment]
We are now getting the emoji from the new url on download on the dev branch. 

I have decided against moving the url variables to the top to make them less magical - each of the download routines itself is closely tied to the content at their respective links and it does not make too much sense to allow to change them. 
Such a change should instead take place when (if) we extract the download functionality itself to make it less hard-coded than it currently is.
