### ISSUE TITLE
Custom typing tool usage

### ISSUE THREAD

**Issue by vaygr** [marty-oehme/bemoji#19]
I'm confused about how custom typing tool selection is supposed to work at https://github.com/marty-oehme/bemoji/blob/main/bemoji#L171.

I'm using [autotype](https://github.com/gemdude46/autotype) for typing, which supports both stdin and the first argument selection.

The workaround is to let bemoji echo output and pipe it to the tool, but that defeats the whole point of supporting custom typing tooling selection that's built in:

```
$ bemoji -ne | autotype
```

**Comment by marty-oehme** [comment]
This was a good catch! 

We are passing the selection contents through to any custom typing (or clipping) tools through stdin. 
However, for custom typing tools specifically, stdin was consumed but not propagated to the tools.

It should now be fixed on the dev branch.
