### ISSUE TITLE
First entry in picker is "No suitable picker tool found."

### ISSUE THREAD

**Issue by cloudlena** [marty-oehme/bemoji#27]
Having `bemenu` installed and in my path, running the command `bemoji -n`, I get "No suitable picker tool found." as the first entry in the picker. Except for that, it works like a charm. All the other entries are actual emoji, and copying them works.

**Comment by marty-oehme** [comment]
Thank you for reporting this!

The immediate fix is to manually take a look in your history file (default `~/.local/share/bemoji-history.txt` for 0.3.0 or `~/.local/state/bemoji-history.txt` for main) to manually find and delete the line from there.

Do you remember if you did not have `bemenu` installed at some point while calling `bemoji`?
I would guess the error message appeared then and now we made it part of your history file.

Your report points to a much more general problem in the code - we output info, debug and warning messages on the same stdout that we use to populate the picker tools! 
That is definitely bad and should not be happening, and I pushed a fix for it.

It points to another issue in that we add entries to the history that should technically not be there, but I believe that is another issue. 
If this works well for you we can probably close this issue and I'll track the other one somewhere else.

**Comment by cloudlena** [comment]
Thanks for looking into this, @marty-oehme!

It indeed is very likely that I didn't have `bemenu` installed when first starting `bemoji` as I intended to use it with `fuzzel`.

Removing the `No suitable picker tool found.` entries from `~/.cache/bemoji-history.txt` did indeed fix the issue :+1:

**Comment by marty-oehme** [comment]
Perfect, this is good to hear.

Then I will consider the immediate issue fixed and I'll have to think about how to fix the bigger history inclusion problem.

Again, thanks for the issue submission! (and hopefully the fixed version will appear in a release soon 😉)
