### ISSUE TITLE
A problem with typing `--delay30` string by xdotool

### ISSUE THREAD

**Issue by arkadiusz-wieczorek** [marty-oehme/bemoji#3]
Hi Marty!

I use `bemoji -t` with instant typing parameter to paste an emoji character into an active input. I've discovered that `xdotool` also typing a following string: `--delay30`:

![image](https://user-images.githubusercontent.com/5663277/148229166-34cf2792-4db0-421b-857c-9568dd446644.png)

So I decided to fix it, here is my PR: https://github.com/marty-oehme/bemoji/pull/2

**Comment by marty-oehme** [comment]
Good catch, I knew there was something left behind when switching my code to enable wtype/ydotool.

I'll check out the PR later today and merge it accordingly!

**Comment by arkadiusz-wieczorek** [comment]
Thank you!
