### ISSUE TITLE
Changing picker to fuzzel not working

### ISSUE THREAD

**Issue by TheRialNiels** [marty-oehme/bemoji#30]
I have changed the picker using the env like this into my .bashrc
export BEMOJI_PICKER_CMD=fuzzel

But now when I try to execute bemoji, the emojis are not being displayed, instead the default fuzzel with the .desktop icons appears

**Comment by ismay** [comment]
You need to use `BEMOJI_PICKER_CMD="fuzzel -d"` if you're setting it manually.

**Comment by marty-oehme** [comment]
Thank you @ismay for providing the answer already. Yes, fuzzel needs to be invoked in its 'dmenu-mode' to work correctly, you can see how we do it in the code itself [here](https://github.com/marty-oehme/bemoji/blob/main/bemoji#L29).

I will consider this closed for now but do let me know if there are additional issues @TheRialNiels!

**Comment by marty-oehme** [comment]
Actually took this opportunity to slightly extend the README with just this example in ab10547
