### ISSUE TITLE
Extra new line is always added with Wayland clipboard

### ISSUE THREAD

**Issue by nonetrix** [marty-oehme/bemoji#32]
When you select a emoji it for some reason adds a new line annoyingly like so
```
💔

```
Not sure if this only effects Wayland or not or what, but also would prefer if it just inputted the emoji which is possible pretty sure

**Comment by TerraReef27** [comment]
Did you try using the -n option?

**Comment by nonetrix** [comment]
That works, but why isn't it default?

**Comment by marty-oehme** [comment]
Thanks @TerraReef27 for helping out, that is exactly it. 

As for it not being default: originally we always added a newline and only later included the option to not have one.
But we also did not want to break the emoji insert for those that already set it up in their key configurations and scripts so we added it as an optional switch.

If we get to a point where we have to implement other larger breaking changes as well we can re-consider switching this around but for the time being I prefer not breaking anything if possible.
