### ISSUE TITLE
Emojis don't get pasted (rofi - i3wm)

### ISSUE THREAD

**Issue by Samueru-sama** [marty-oehme/bemoji#35]
This is on artix linux, using rofi and i3-wm.

I've tried the aur package and the script in the releases directly.

The script works and gives me a list of emojis, but when I select one nothing happens, nothing gets pasted and there is no error in the terminal either. 

Warning that I have `$XDG_***_HOME` variables defined in `~/Local` so I don't know if this is what's causing the issue.

edit: yes I have xdotool and xclip.

edit2: I can see that the list of emojis gets put in `$XDG_DATA_HOME/bemoji` as well.

**Comment by Samueru-sama** [comment]
Welp, the issue ended up me not using the `-t` flag. I'm very sorry 😅

**Comment by marty-oehme** [comment]
No worries, glad it it working well for you now.

Don't hesitate to reach out again if you have any other issues or anything else comes up!
