### ISSUE TITLE
-t typing does not work

### ISSUE THREAD

**Issue by justin8** [marty-oehme/bemoji#39]
Hey,

I'm using bemoji 0.4.0 installed from the AUR on Arch - when using `-c` or `-e` it behaves as expected, however with `-t` I can't seem to get it to type the characters to any in-focus window. I've tried with both wofi and rofi with no luck so far.

**Comment by Fizzial** [comment]
Do you have `xdotool` (xorg) or `wtype` (wayland) installed? They are dependencies for that feature to work

**Comment by justin8** [comment]
Ah, you're right. I swapped from X to Wayland recently and only had xdotool installed.
