### ISSUE TITLE
Consider renaming the project to "bashmoji"

### ISSUE THREAD

**Issue by markstos** [marty-oehme/bemoji#4]
There is another more populate software project named "bemoji" , that fills up most of the search results of the first couple pages when searching exactly for the name:

https://www.google.com/search?hl=en&q=bemoji

Also consider adding some Github tags to make it easier to find, as the `dmenu-emoji` project did.  This project generally works great, but is a little hard to find.

![image](https://user-images.githubusercontent.com/25829/176255472-dbc1b5da-b751-46f9-9c96-51147702e806.png)

**Comment by marty-oehme** [comment]
An interesting idea. For now I think I am honestly not too bothered by the discoverability (also shows up 8th spot on the google search for me, just after some android and instagram stuff). Do you think there are large negatives aside from initial discoverability for the little project?

The tags are probably a good idea however, I'll take a minute to fix it.

Also, your google search link showed me that the project is now also packaged as an Arch-AUR package, so thanks for that! :)

**Comment by marty-oehme** [comment]
Nonetheless thank for the ideas, perhaps in the future as it gains more traction we can reconsider.

**Comment by kulothunganug** [comment]
I suggest reconsidering the current project name "bemoji" as it may give the impression that it is exclusively for the "bemenu" program launcher, when in fact it is designed to work with multiple program launchers.
