### ISSUE TITLE
Bemenu Args

### ISSUE THREAD

**Issue by niksingh710** [marty-oehme/bemoji#7]
How can i pass bemenu arguments?

**Comment by marty-oehme** [comment]
Currently what you would do is use bemenu as a custom 'picker' command with all options you want passed.
The custom picker is set through the `BEMOJI_PICKER_CMD`.

For example, 

```bash
BEMOJI_PICKER_CMD="bemenu -c" bemoji
``` 

or

```bash
export BEMOJI_PICKER_CMD="bemenu -b"
bemoji
```

to have the option set more permanently.
