### ISSUE TITLE
Copy and type

### ISSUE THREAD

**Issue by niksingh710** [marty-oehme/bemoji#8]
How can i copy and type the emoji at the same time ?

**Comment by marty-oehme** [comment]
That is currently not supported, or at least I wouldn't know how to do
it with just the tool itself.

You may be able to hack something together with moreutils
[pee](https://manned.org/pee.1) but I'm not even sure how you would go
about doing that.

But I am curious, what would a use case for this be?

**Comment by niksingh710** [comment]
I created a [pr](https://github.com/marty-oehme/bemoji/pull/9#issue-1307165952) for what the feature I wanted to be in bemoji.

I use vim and being in normal mode and seeing the emoji is not written sometimes get annoying so having the emoji in the clipboard makes it easier.

**Comment by niksingh710** [comment]
Could have used `tee`. but that way was not going through how the other code was implemented so opted for the long way.

**Comment by marty-oehme** [comment]
Closed by 7e8fc0c51a6eb27d370c3d6460c9eace9559cab8

**Comment by niksingh710** [comment]
Have you given any thought to [this Feature](https://github.com/marty-oehme/bemoji/issues/10)?

Adding other Unicode or stuff ??
